Nama : Mochammad Zidan Ardany

Kelas : Atlas

# Operasi Matematika & Numpy

In [2]:
import numpy as np

## Pengenalan array

In [3]:
# 1D array
a = np.array([[1, 3, 0], [2, 4, 1], [3, 6, 7]])
print('banyaknya entry =', a.size)
print('dimensi array =', a.ndim)
print('ukuran array =', a.shape)

banyaknya entry = 9
dimensi array = 2
ukuran array = (3, 3)


In [4]:
# Slicing
a[:]

array([[1, 3, 0],
       [2, 4, 1],
       [3, 6, 7]])

In [5]:
# Slicing
a[:2]

array([[1, 3, 0],
       [2, 4, 1]])

In [6]:
# Slicing
a[2]

array([3, 6, 7])

In [7]:
# Slicing
a[1:]

array([[2, 4, 1],
       [3, 6, 7]])

In [8]:
print('a[1:3] =', a[1:3])
print('a[:3] =', a[:3])                                                                                                                                                                                                                                                                                                                                                                                                                                                                  

a[1:3] = [[2 4 1]
 [3 6 7]]
a[:3] = [[1 3 0]
 [2 4 1]
 [3 6 7]]


In [9]:
# 2D Array (Matriks)
A = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


## Latihan-2 (2D array)

In [10]:
# lengkapi kodingan berikut
print('banyaknya entry =', A.size)
print('dimensi array =', A.ndim)
print('ukuran array =', A.shape)

banyaknya entry = 9
dimensi array = 2
ukuran array = (3, 3)


In [11]:
# Slicing
print('baris ke-2 =', A[1])
print('entry ke-2 & 3 baris ke-2 =', A[1, 1:])
print('entry pertama & 2 kolom ke-2 =', A[:2,1])

baris ke-2 = [4 5 6]
entry ke-2 & 3 baris ke-2 = [5 6]
entry pertama & 2 kolom ke-2 = [2 5]


## Latihan-3 (Slicing)

In [12]:
# lengkapi kodingan berikut
print('baris ke-3 =', A[2])
print('entry ke-1 & 2 baris ke-3 =', A[2,0:2])
print('entry ke-2 & 3 kolom ke-3 =', A[1:,2])

baris ke-3 = [7 8 9]
entry ke-1 & 2 baris ke-3 = [7 8]
entry ke-2 & 3 kolom ke-3 = [6 9]


## Operasi Matematika di Numpy

In [13]:
C = A*A
print('perkalian antar entry = ')
print(C)

perkalian antar entry = 
[[ 1  4  9]
 [16 25 36]
 [49 64 81]]


In [14]:
print('perkalian matriks =')
print(np.matmul(A,A))

perkalian matriks =
[[ 30  36  42]
 [ 66  81  96]
 [102 126 150]]


berbeda dengan perkalian matriks biasa, perkalian matriks antar entry mengalikan masing masing entry yang sama posisinya

In [15]:
print('determinan matriks A =', np.linalg.det(A))
print('determinan matriks C =', np.linalg.det(C))

determinan matriks A = 0.0
determinan matriks C = -216.00000000000006


In [16]:
print('nilai dan vektor eigen matriks A =', np.linalg.eig(A))

nilai dan vektor eigen matriks A = (array([ 1.61168440e+01, -1.11684397e+00, -1.30367773e-15]), array([[-0.23197069, -0.78583024,  0.40824829],
       [-0.52532209, -0.08675134, -0.81649658],
       [-0.8186735 ,  0.61232756,  0.40824829]]))


In [17]:
print('nilai eigen matriks A =', np.linalg.eig(A)[0])

nilai eigen matriks A = [ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15]


In [18]:
print('vektor eigen matriks A =', np.linalg.eig(A)[1])

vektor eigen matriks A = [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [20]:
# mengambil eigen vector pertama [-0.23197069 -0.78583024  0.40824829]
e_vec = np.linalg.eig(A)[1][:, 0]
# mengambil eigen value pertama (1.61168440e+01)
e_val = np.linalg.eig(A)[0][0]

In [21]:
# hasil A * eigen vector
print(np.matmul(A, e_vec))

[ -3.73863537  -8.46653421 -13.19443305]


In [26]:
# hasil eigen value * eigen vector (Hasilnya sama)
print(e_val*e_vec)

[ -3.73863537  -8.46653421 -13.19443305]


## Latihan-4 (Operasi matriks)

In [27]:
A = np.array([[1, 2], [7, 8]])
B = np.array([[3, 5], [1, 6]])

Hitunglah:
*   2*A
*   2+A
*   A+B
*   A-B
*   determinan A
*   Invers dari B, simpan jadi matriks D
*   transpose D
*   nilai eigen dan vektor eigen dari A dan B


In [37]:
# Ketik kode disini
print("Hasil dari 2*A :\n", 2*A)
print("Hasil dari 2+A :\n", 2+A)
print("Hasil dari A+B :\n", A+B)
print("Hasil dari A-B :\n", A-B)
print("Hasil dari Determinan A :", np.linalg.det(A))

D = np.linalg.inv(B)
print("Hasil dari invers B :\n", D)
print("Hasil dari transpose D :\n", D.T)
print("nilai eigen matriks A =", np.linalg.eig(A)[0])
print("vektor eigen matriks A =\n", np.linalg.eig(A)[1])
print("nilai eigen matriks B =", np.linalg.eig(B)[0])
print("vektor eigen matriks B =\n", np.linalg.eig(B)[1])

Hasil dari 2*A :
 [[ 2  4]
 [14 16]]
Hasil dari 2+A :
 [[ 3  4]
 [ 9 10]]
Hasil dari A+B :
 [[ 4  7]
 [ 8 14]]
Hasil dari A-B :
 [[-2 -3]
 [ 6  2]]
Hasil dari Determinan A : -6.0
Hasil dari invers B :
 [[ 0.46153846 -0.38461538]
 [-0.07692308  0.23076923]]
Hasil dari transpose D :
 [[ 0.46153846 -0.07692308]
 [-0.38461538  0.23076923]]
nilai eigen matriks A = [-0.62347538  9.62347538]
vektor eigen matriks A =
 [[-0.77640358 -0.22592838]
 [ 0.63023605 -0.97414391]]
nilai eigen matriks B = [1.8074176 7.1925824]
vektor eigen matriks B =
 [[-0.97271381 -0.76626443]
 [ 0.23200828 -0.64252535]]


Apa perbedaan dari B*D (perkalian antar entry di B dan D) dan BD (perkalian matriks B dan D)?

In [36]:
# Tunjukkan bedanya di kodingan di bawah ini
# perkalian antar entry
F = B*D
print('perkalian antar entry =')  
print(F)
# perkalian matriks biasa
print(np.matmul(B,D))                                                                                                                                                                                                                                          

perkalian antar entry =
[[ 1.38461538 -1.92307692]
 [-0.07692308  1.38461538]]
[[ 1.00000000e+00 -1.11022302e-16]
 [ 1.11022302e-16  1.00000000e+00]]
